name: smoke_log
description: "A smoke logging application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^5.4.0
  cloud_firestore: ^4.15.9
  intl: ^0.19.0
  provider: ^6.1.1
  flutter_riverpod: ^2.6.1
  fl_chart: ^0.68.0
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.2
  connectivity_plus: ^6.1.3
  sign_in_with_apple: ^5.0.0
  google_sign_in_mocks: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  firebase_auth_mocks: ^0.13.0
  network_image_mock: ^2.1.1
  flutter_lints: ^4.0.0
  flutter_driver:
    sdk: flutter
  mocktail: ^1.0.4
  fake_cloud_firestore: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png
