name: smoke_log
description: "A smoke logging application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  google_sign_in: ^5.4.0
  cloud_firestore: ^4.15.9
  intl: ^0.19.0
  provider: ^6.1.1
  flutter_riverpod: ^2.6.1
  fl_chart: ^0.68.0
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
