# Devices to take screenshots on
devices([
  "Screenshot-iPhone16", # From iOS 18.2
  # "iPhone 15", # From iOS 17.2
  # "iPad Pro (12.9-inch) (6th generation)" # From iOS 17.2
])

# Languages
languages([
  "en-US"
])

# The name of the scheme to use for UI tests
scheme("RunnerUITests")

# Where to store the screenshots - use absolute path
output_directory(File.expand_path("~/Documents/smoke_log/ios/screenshots"))

# Clear previous screenshots before creating new ones
clear_previous_screenshots(true)

# Additional config for better screenshots
concurrent_simulators(false)
stop_after_first_error(true)

# Override status bar for consistent screenshots
override_status_bar(true)

# Arguments to pass to the app on launch
launch_arguments(["-FASTLANE_SNAPSHOT", "YES"])

# For more information about all available options run
# fastlane action snapshot
